### ISSUE TITLE
同步到微信公众号存在bug

### ISSUE THREAD

**Issue by NHPT** [qiuzhangsaer/WeChatDraft#3]
当文章中通过插件添加目录树时：
![image](https://github.com/qiuzhangsaer/WeChatDraft/assets/42366434/d7ae89d1-38d0-4b7e-ace7-daad910de450)
点击发布无法同步到微信公众号，报错如下：
![image](https://github.com/qiuzhangsaer/WeChatDraft/assets/42366434/74ea52f5-8148-4821-bb29-a6622ba54dc0)
原因是微信会丢弃#[a-zA-Z0-9]格式的数据，解决方法：将#替换为\#
已提交pull requests

**Comment by qiuzhangsaer** [comment]
已通过
