### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by jiaotiliu** [qiuzhangsaer/WeChatDraft#4]
![](https://tyblog.s3.us-west-004.backblazeb2.com/littlepark/2023/11/20231120215601.png)

报错

**Comment by qiuzhangsaer** [comment]
有个事情忘了写到注释里，微信公众号素材库要提前上传一个图片命名为typecho.jpg当做封面使用

**Comment by qiuzhangsaer** [comment]
详细的使用说明可以到此地址查看[https://www.xvkes.cn/archives/290/](https://www.xvkes.cn/archives/290/)

**Comment by jiaotiliu** [comment]
![image](https://github.com/qiuzhangsaer/WeChatDraft/assets/134895892/d030f387-5ed4-4b0b-af6a-b45242d60c31)

添加了封面图可以了。但是有的文章可以发表，有的也会报错。换了一个错误

**Comment by jiaotiliu** [comment]
> ![image](https://user-images.githubusercontent.com/134895892/284302214-d030f387-5ed4-4b0b-af6a-b45242d60c31.png)
> 
> 添加了封面图可以了。但是有的文章可以发表，有的也会报错。换了一个错误

明白了，可能是我文章图片格式的问题，我文章的图片格式为webp

**Comment by qiuzhangsaer** [comment]
图片最好用常见的通用格式，我也不确定微信支持哪些图片格式的上传，没仔细看微信文档

**Comment by jiaotiliu** [comment]
十分感谢
